Better documentations
tesar-tech/BlazorStatic pull request #18
Opened 2024-06-25 16:59 UTC by MeltyObserver

clean and improve the documentations

## TODO

- [x] rewrite the main readme
- [ ] rewrite the [new-start file](<https://github.com/tesar-tech/BlazorStatic/blob/master/BlazorStaticWebsite/Content/Docs/new-start.md>) (change it to `in-depth-guide`?)
- [ ] verify grammar and vocabulary.

is there anything else i forgot about?

2024-06-25 17:02 UTC, MeltyObserver commented
I tried to keep the main Readme as simple and straightforward as possible.

2024-06-26 08:15 UTC, tesar-tech requested changes
Nice. This is a much better version. It is not an easy task to explain things to people from the position of someone who understands it well. Thanks for the contribution.

2024-06-26 08:15 UTC, tesar-tech commented on README.md
> +### Features
Also second level heading here? `##`

2024-06-26 08:15 UTC, tesar-tech commented on README.md
> +- Easily parse and consume markdown files.
I like how brief and on point it is!

2024-06-26 08:15 UTC, tesar-tech commented on README.md
> +#### Cloning the project
I wouldn't put this in main "how to" guide. It makes it look complicated.

2024-06-27 03:09 UTC, MeltyObserver commented
It just occured to me, Should I add a "limitations" section below the features?

2024-06-27 13:00 UTC, tesar-tech commented
> It just occured to me, Should I add a "limitations" section below the features?

Hm, probably yes, some sort of..

But what are the limitations? Limitations of static site generator in general? Limitations like "missing features"? I would name it in more positive manner, something like: "Coming soon", etc.. 
Or a different kind of limitations?

2024-06-27 13:58 UTC, MeltyObserver commented
I meant like a warning to inform users that this library cannot convert their c# code to JavaScript, so if they have any interactive component that relies on c# it won't work.

2024-06-27 17:40 UTC, tesar-tech commented
I think it's not necessary. This is already an "issue" with SSR and people who are willing to use any static site generator do understand that.

2024-07-06 11:24 UTC, merged

2024-07-06 11:46 UTC, tesar-tech commented
Thanks for it.

I have done some edits after.
Now it all should be all more understandable for other users.